# Decrypt Message
Decoded message replit: https://replit.com/@Mr-Adams/encoded-message-no-punctuation#main.py
* I used frequency analysis and then used the key to decrypt the message

# Encrypt Message
* I would use a playfair cipher to encryt my message.
* I think this method is quite creative and can provide some security by keeping the keyword secret
* I love the three rules from the video to encode the message.
* Secret keyword = love 
* secret message = Iloveyou 
* encoded message = OHLOWVW

* Test IL together first and they would follow rule three getting HO
* Test OV together first and they would follow rule two shifting each letter one to the right getting VE
* Test EY together first and they would follow rule three getting WV
* Test UX together first and they would follow rule two getting ZW



## Another option to encrypt:
* I thought about using a ceaser style cipher, but have the key shift as well.
* this would work by having an initial shift of lets say 3 and every 6 letters the shift gets doubled.  This would need a message of decent length to work and ensure that the key a frequency analysis does not easily identify the key to decrypt the message.
* this would need a method to ignore non letter characters in the message
